### ISSUE TITLE
Can we use multiple computing nodes (Google accounts) for production purpose?

### ISSUE THREAD

**Issue by fqqlsun** [fqqlsun/LEAF_production#4]
It is desired that we can use multiple computing nodes (Google accounts) to speed up production. Even each account get more exporting channels already. If so, how can we automatically launch executions with different accounts?

**Comment by rfernand387** [comment]
Response from Sean Wohltman.

No harm, no foul on the sharding, Richard - sorry to bring the heavy ToS hand - it's one of those things that vexes us. 

Under the SA, we had scoped 5 reserved batch processors a month, but I feel like that will be too restrictive - I'm going to recommend 10 at a minimum here and I can put in that request now. 

I just need to know what project Lixin will be using. 

The list value of the 10 batch reservations would be ~$100K, but since we're under the SA we'll just track this (so you would see the usage for budgeting in the future) - there's no additional resource / charge for this right now. 

The minimum time for a batch reservation right now is 1 month. We have to do a bit of manual code pushing internally to get it set up at the moment. 

Let me know the project and I'll get the 10 allocated for at least Feb 1 - Feb 28.
